#!/usr/bin/env python
import sys

for line in sys.stdin:
    o = ''
    line = ''.join(j for j in line if not j.isdigit())
    for i in line.replace('[m',''):
        if i.isalpha():
            o+=i
        if i==' ':
            o+=i
    o+='\n'
    sys.stdout.write(o)

